config/routes.rb
Rails.application.routes.draw do
  # get 'movie/index'
  #
  # get 'movie/show'

  root 'movies#index'

  resources :collections do
    post :upvote, on: :member
    post :downvote, on: :member
  end

  # resources :users do
  #   resources :collections do
  #     post :upvote, on: :member
  #     post :downvote, on: :member
  #   end
  # end


  get '/index', to: 'movies#index'
  get '/show', to: 'movies#show'


  get 'auth/logout' => 'auth#logout'
  get 'auth/failure' => 'auth#failure'
  get 'auth/:provider/callback' => 'auth#callback'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :votes, :dependent => :delete_all

  def upvotes
    votes.sum(:upvote)
  end

  def downvotes
    votes.sum(:downvote)
  end

  def calc_points
    points = upvotes - downvotes

    update_attributes(points: points)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :collections
  has_many :votes

  def self.create_with_omniauth(auth)
    user = find_or_create_by(uid: auth[‘uid’], provider:  auth[‘provider’])
    user.email = “#{auth[‘uid’]}@#{auth[‘provider’]}.com”
    user.password = auth[‘uid’]
    user.name = auth[‘info’][‘name’]
    if User.exists?(user)
      user
    else
      user.save!
      user
    end
  end

  def owns_collection?(collection)
    self == collection.user
  end

  def upvote(collection)
    votes.create(upvote: 1, collection: collection)
  end

  def upvoted?(collection)
    votes.exists?(upvote: 1, collection: collection)
  end

  def remove_vote(collection)
    votes.find_by(collection: collection).destroy
  end

  def downvote(collection)
    votes.create(downvote: 1, collection: collection)
  end

  def downvoted?(collection)
    votes.exists?(downvote: 1, collection: collection)
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :collection
  
  validates :user_id, uniqueness: { scope: :collection_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def prevent_unauthorized_user_access
    redirect_to root_path, notice: 'sorry, you cannot access that page', status: :found unless logged_in?
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    current_user.nil? ? false : true
  end

  def scrape_netflix
    require 'open-uri'
    doc = Nokogiri::HTML(open("https://www.finder.com/sg/netflix-movies"))

    netflix = doc.css('.custom-table')

    netflixArray= []
    doc.xpath('//*/table/tbody/tr/td[1]').each do |netflix|
      netflixArray << netflix.text
    end
    p netflixArray
  end

  def flixlist
    @flixlist = scrape_netflix
  end


  helper_method :current_user, :logged_in?, :flixlist
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def callback
    provider_user = request.env['omniauth.auth']

    user = User.find_or_create_by(provider_id: provider_user['uid'], provider: params[:provider]) do |u|
      u.provider_hash = provider_user['credentials']['token']
      u.name = provider_user['info']['name']
      u.email = provider_user['info']['email']
    end

    session[:user_id] = user.id
    # redirect_to collections_path(session[:user_id])
    redirect_to request.env['omniauth.origin']
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  def failure
    render plain: 'this is a failure'
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :current_user, :flixlist
  before_action :prevent_unauthorized_user_access, except: [:index, :show]

  def index
    @users = User.all
    @votes = Vote.all
    @collections = Collection.where("user_id = ?", current_user.id)
    @flixlist
  end

  def show
    @users = User.all
    @votes = Vote.all

    @user = User.where("id = ?", params[:id]).first

    @collections = Collection.where("user_id = ?", params[:id]).order('points DESC')

    if current_user
      @my_movies = Collection.where("user_id = ?", current_user.id)
    end
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = current_user.collections.new(collection_params)

    if @collection.save
      redirect_to collection_path(@collection.user_id), notice: "Added to collection"
    else
      redirect_to root_path
    end
  end

  def destroy
    collection = Collection.find_by(id: params[:id])
      collection.destroy
      redirect_to collection_path(current_user.id), notice: 'Collection successfully deleted'
  end


  def upvote
    collection = Collection.find_by(id: params[:id])
    if current_user.upvoted?(collection)
      current_user.remove_vote(collection)
    elsif current_user.downvoted?(collection)
    current_user.remove_vote(collection)
    current_user.upvote(collection)
    else
      current_user.upvote(collection)
    end

    collection.calc_points
    redirect_to collection_path(collection.user_id), notice: "you kenot"
  end

  def downvote
    collection = Collection.find_by(id: params[:id])
    if current_user.downvoted?(collection)
      current_user.remove_vote(collection)
    elsif current_user.upvoted?(collection)
      current_user.remove_vote(collection)
      current_user.downvote(collection)
    else
      current_user.downvote(collection)
    end

    collection.calc_points
    redirect_to collection_path(collection.user_id)
  end

  private
  def collection_params
    params.require(:collection).permit(:movie_id, :user_id, :movie_id, :movie_title, :movie_poster, :movie_year, :movie_plot, :movie_runtime, :movie_genre, :movie_metascore, :movie_imdbRating)
  end

end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def index
    search = params[:q]
		if search
			resp = Typhoeus.get("http://www.omdbapi.com", params: {s: search})
			@movies = JSON.parse(resp.body)["Search"]
      p resp.body
    else
			@movies = []
		end
  end

  def show
    imdbID = params[:q]
		if imdbID
			resp = Typhoeus.get("http://www.omdbapi.com", params: {i: imdbID})
			@movie = JSON.parse(resp.body)
      p resp.body
		else
			@movie = {}
		end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :flixlist


  def index
    search = params[:q]
		if search
			resp = Typhoeus.get("http://www.omdbapi.com", params: {s: search})
			@movies = JSON.parse(resp.body)["Search"]
      # p resp.body
    else
			@movies = []
		end
    @collections = Collection.select(:movie_poster, :movie_id, :movie_title).distinct.order("movie_title ASC")
    @users = User.all

    @flixlist
  end

  # def scrape_netflix
  #   require 'open-uri'
  #   doc = Nokogiri::HTML(open("https://www.finder.com/sg/netflix-movies"))
  #
  #   netflix = doc.css('.custom-table')
  #
  #   netflixArray= []
  #   doc.xpath('//*/table/tbody/tr/td[1]').each do |netflix|
  #     netflixArray << netflix.text
  #   end
  #   p netflixArray
  # end

  def show
    imdbID = params[:q]
		if imdbID
			resp = Typhoeus.get("http://www.omdbapi.com", params: {i: imdbID})
			@movie = JSON.parse(resp.body)
      p resp.body
		else
			@movie = {}
		end

    if current_user
      @user_has_movie = Collection.where(movie_id: (params[:q]), user_id: current_user.id).first
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/collections/index.html.erb
<h1>my collection</h1>


<%= render "partials/collection" %>

app/views/collections/show.html.erb
<% if current_user && @user.name == current_user.name %>
<h3>My collection</h3>
<% else %>
<h3><%= @user.name %>'s collection</h3>
<% end %>

<% if !current_user %>
<div>
  <h4>Log in to vote on <%= @user.name %>'s movies!</h4>
  <%= link_to "Login with Facebook", "/auth/facebook", class: "btn btn-default" %>
  <%= link_to "Login with Twitter", "/auth/twitter", class: "btn btn-default" %>
</div>
<% end %>
<br>

<%= render "partials/collection" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>what's next? v1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>

    <%= render "partials/header" %>

    <div class="container-fluid">
      <%= yield %>
    </div>

    <%= render "partials/footer" %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/movie/index.html.erb
<div class="center">
  <h1>Movie#index</h1>
  <%= current_user.inspect %>
<p>Find me in app/views/movie/index.html.erb</p>

<%= form_tag("/index", method: "get") do %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>


<% @movies.each do |movie| %>

<a href='/show?q=<%= movie["imdbID"] %>'><img class="movie-img" src="<%= movie["Poster"] %>" alt="<%= movie["Title"] %>" /></a>


<% end %>
</div>

app/views/movie/show.html.erb
<h1>Movie#show</h1>
<p>Find me in app/views/movie/show.html.erb</p>


<div class="movie-container">
  <div class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object" src="<%= @movie["Poster"] %>" alt="<%= @movie["Title"] %>" />
      </a>
    </div>
    <div class="media-body">
      <h1><%= @movie["Title"] %></h1>
      <h2><%= @movie["Year"] %></h2>
      <p><%= @movie["Plot"] %></p>
      <p><%= @movie["Runtime"] %></p>
      <p><%= @movie["Released"] %></p>
      <p><%= @movie["Genre"] %></p>
      <p><%= @movie["Director"] %></p>
      <p><%= @movie["Actors"] %></p>
      <p><%= @movie["Awards"] %></p>
      <p><%= @movie["Metascore"] %></p>
      <p><%= @movie["imdbRating"] %></p>
      <p><%= @movie["imdbVotes"] %></p>
      <p><%= @movie["imdbID"] %></p>
      <%= link_to('add to list', collection_index_path, :class => 'btn btn-large btn-info')  %>

      <%= form_for :collection, url: {:controller => 'collection', :action => 'create'} do |t| %>
      <%= t.hidden_field :movie_id, :value => @movie["imdbID"] %>
      <%= t.hidden_field :user_id, :value => current_user.id %>
      <%= t.submit "RSVP", :class => "btn-info" %>
      <% end %>

    </div>
  </div>


</div>

app/views/movies/index.html.erb
<% if !logged_in? && @movies.length == 0 %>
  <div class="row row-eq-height">

    <div class="col-xs-12 col-sm-6 col-md-5 col-md-offset-1">
      <%= image_tag "whatnext.png", class: "img-responsive" %>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-5 text-center is-flex">
      <div class="subtext">
        <h3>Friends don't let friends watch bad movies.</h3>
        <h4>Login to create collections and vote.</h4>
        <%= link_to "Login with Facebook", "/auth/facebook", class:"btn btn-primary" %>
        <%= link_to "Login with Twitter", "/auth/twitter", class:"btn btn-info"  %>
        <%= form_tag("/index", method: "get", class: "navbar-form") do %>
        <h4>Find a movie...</h4>
        <%= text_field_tag(:q, nil, placeholder: "search by movie title", class: "form-control") %>
        <%= submit_tag("Search", class: "btn btn-default") %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="text-center">
<% if @movies.length > 0 %>
  <% @movies.each do |movie| %>
  <a href='/show?q=<%= movie["imdbID"] %>'>
    <img class="movie-img" src="<%= movie["Poster"] %>" alt="<%= movie["Title"] %>" />
    <% if @flixlist.include?(movie["Title"]) %>
    <%= image_tag("netflixsq.png", class: "netflix-icon") %>
    <% end %>
  </a>

  <% end %>

<% else %>
<div class="text-center">
  <h3>Browse our users' collections</h3>
  <ul>
    <% @users.each do |user| %>
    <a href='/collections/<%= user.id %>'>
      <li><%= user.name %></li>
    </a>
    <% end %>
  </ul>
</div>

<div class="text-center">
  <h3>Browse movies in our users' collections...</h3>
  <% @collections.each do |collection| %>
  <a href='/show?q=<%= collection.movie_id %>'>
    <img class="movie-img" src="<%= collection.movie_poster %>" alt="<%= collection.movie_title %>" />
    <% if @flixlist.include?(collection.movie_title) %>
    <%= image_tag("netflixsq.png", class: "netflix-icon") %>
    <% end %>
  </a>
  <% end %>
</div>
<% end %>

app/views/movies/show.html.erb
<div class="row center">
  <div class="col-xs-12 col-sm-6 col-md-5 col-md-offset-1 col-lg-4 col-lg-offset-2 text-center nflx">
    <img class="img-responsive" src="<%= @movie["Poster"] %>" alt="<%= @movie["Title"] %>" />
    <% if @flixlist.include?(@movie["Title"]) %>
    <%= image_tag("netflixsq.png", class: "netflix-page") %>
    <% end %>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-5 col-lg-3">
    <h1><%= @movie["Title"] %>
      <small>(<%= @movie["Year"] %>)</small></h1>
    <p><%= @movie["Plot"] %></p>
    <p>Runtime: <%= @movie["Runtime"] %></p>
    <p>Released: <%= @movie["Released"] %></p>
    <p>Genre: <%= @movie["Genre"] %></p>
    <p>Director: <%= @movie["Director"] %></p>
    <p>Actors: <%= @movie["Actors"] %></p>
    <p>Awards: <%= @movie["Awards"] %></p>
    <p>Metascore: <%= @movie["Metascore"] %></p>
    <p>imdb Rating: <%= @movie["imdbRating"] %>/10 based on <%= @movie["imdbVotes"] %> votes.</p>
    <p><a href="http://imdb.com/title/<%= @movie["imdbID"] %>">View on ImDB</a></p>

    <% if !current_user %>
      <h4>Want to add this to your own collection?</h4>
      <%= link_to "Login with Facebook", "/auth/facebook", class: "btn btn-primary" %>
      <%= link_to "Login with Twitter", "/auth/twitter", class: "btn btn-info" %>

    <% elsif !@user_has_movie %>
      <%= form_for :collection, url: {:controller => 'collections', :action => 'create'} do |t| %>

      <%= t.hidden_field :user_id, :value => current_user %>
      <%= t.hidden_field :movie_id, :value => @movie["imdbID"] %>
      <%= t.hidden_field :movie_title, :value => @movie["Title"] %>
      <%= t.hidden_field :movie_poster, :value => @movie["Poster"] %>
      <%= t.hidden_field :movie_year, :value => @movie["Year"] %>
      <%= t.hidden_field :movie_plot, :value => @movie["Plot"] %>
      <%= t.hidden_field :movie_runtime, :value => @movie["Runtime"] %>
      <%= t.hidden_field :movie_genre, :value => @movie["Genre"] %>
      <%= t.hidden_field :movie_metascore, :value => @movie["Metascore"] %>
      <%= t.hidden_field :movie_imdbRating, :value => @movie["imdbRating"] %>

      <%= t.submit "add to my collection", :class => "btn btn-info" %>
      <% end %>

    <% else @user_has_movie %>
      <a href="/collections/<%= current_user.id %>"><button class="btn btn-success">View this movie in my collection</button></a>
    <% end %>
  </div>
</div>

app/views/partials/_collection.html.erb
<div class="row">

  <div class="col-sm-9 col-md-8 col-md-offset-1">
    <div>
      <% if @collections.count == 0 %>
        <%= image_tag("nothinghere.jpg", class: "img-responsive") %>
      <% else %>
        <% @collections.each do |collection| %>
          <div class="row coll">

            <div class="col-xs-5 col-sm-2 text-center info">
                <% if current_user && current_user.upvoted?(collection) %>
                  <%= button_to "watch!", upvote_collection_path(collection), method: :post, class: "btn btn-sm btn-success" %>
                <% elsif current_user %>
                  <%= button_to "watch!", upvote_collection_path(collection), method: :post, class: "btn btn-default" %>
                <% end %>


                <% if current_user && current_user.downvoted?(collection) %>
                  <%= button_to "meh", downvote_collection_path(collection), method: :post, class: "btn btn-sm btn-warning" %>
                <% elsif current_user %>
                  <%= button_to "meh", downvote_collection_path(collection), method: :post, class: "btn btn-default" %>
                <% end %>

                <div class="points">
                  <h3><%= collection.points %></h3>
                </div>

                <% if logged_in? && current_user.id == collection.user_id %>
                  <%= link_to "X", collection, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>

                <% elsif logged_in? && current_user.id != collection.user_id %>
                  <% if @my_movies.where("movie_title = ?", collection.movie_title).first %>
                  <%= link_to "X", collection, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
                  <% else %>

                  <%= form_for :collection, url: {:controller => 'collections', :action => 'create'} do |t| %>

                  <%= t.hidden_field :user_id, :value => current_user %>
                  <%= t.hidden_field :movie_id, :value => collection.movie_id %>
                  <%= t.hidden_field :movie_title, :value => collection.movie_title %>
                  <%= t.hidden_field :movie_poster, :value => collection.movie_poster %>
                  <%= t.hidden_field :movie_year, :value => collection.movie_year %>
                  <%= t.hidden_field :movie_plot, :value => collection.movie_plot %>
                  <%= t.hidden_field :movie_runtime, :value => collection.movie_runtime %>
                  <%= t.hidden_field :movie_genre, :value => collection.movie_genre %>
                  <%= t.hidden_field :movie_metascore, :value => collection.movie_metascore %>
                  <%= t.hidden_field :movie_imdbRating, :value => collection.movie_imdbRating %>

                  <%= t.submit "+", :class => "btn btn-info" %>
                  <% end %>
                  <% end %>
                  <% end %>


            </div>

            <div class="col-xs-7 col-sm-4 colflix">
              <a href='/show?q=<%= collection.movie_id %>'>
                <img class="indiv" src="<%= collection.movie_poster %>" alt="<%= collection.movie_title %>">
              </a>
              <% if @flixlist.include?(collection.movie_title) %>
              <%= image_tag("netflixsq.png", class: "netflix-list") %>
              <% end %>
            </div>

            <div class="col-xs-12 col-sm-6 no-show">
              <h4 class="media-heading no-show"><%= collection.movie_title %></h4>
              <p><%= collection.movie_plot %></p>
              <p>Upvotes:
                <% @votes.each do |vote| %>
                  <% if collection.id == vote.collection_id && vote.upvote == 1 %>
                  <span class="name"><%= User.find(vote.user_id).name %></span>
                  <% end %>
                <% end %>
              </p>
              <p>Downvotes:
                <% @votes.each do |vote| %>
                  <% if collection.id == vote.collection_id && vote.downvote == 1 %>
                  <span class="name"><%= User.find(vote.user_id).name %></span>
                  <% end %>
                <% end %>
              </p>

              <% if !logged_in? %>
                <h5>Log in to add this to your movies!</h5>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-sm-3 col-md-3">
    <section>
      <h4>Browse other users' collections</h4>
      <ul>
        <% @users.each do |user| %>
        <li><a href="/collections/<%= user.id %>"><%= user.name %></a></li>
        <% end %>
      </ul>
    </section>
  </div>
</div>

app/views/partials/_footer.html.erb
<footer class="footer">
    <div>
      Made with
      &#9825;,
      &#9835; and
      &#9749;
    </div>
  </footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container text-center">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <%= image_tag "logo.jpg", :style => "height: 40px; width: 40px; margin: -10px" %>
        </a>
      </div>

        <%= form_tag("/index", method: "get", class: "navbar-form navbar-left form-inline") do %>
        <%= text_field_tag(:q, nil, placeholder: "search by movie title", class: "form-control") %>
        <%= submit_tag("Search", class: "btn btn-default") %>
        <% end %>


    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><a href="/collections/<%= current_user.id %>"><%= current_user.name %> (<%= current_user.provider %>)</a></li>
          <li><%= link_to "Logout", auth_logout_path %></li>
        <% else %>
          <li><%= link_to "Login with Facebook", "/auth/facebook" %></li>
          <li><%= link_to "Login with Twitter", "/auth/twitter" %></li>
        <% end %>
      </ul>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_users.html.erb
<div style="background-color: lightcyan">
  <section>
    Browse other users' collections
    <ul>
  <% @users.each do |user| %>
    <li>
      <a href="/collections/<%= user.id %>">
        <%= user.name %>
      </a>
    </li>
  <% end %>
</ul>
</section>
</div>